spring.application.name=backend
# H2-tietokanta muistissa
spring.datasource.url=jdbc:h2:mem:reservationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Anna Hibernaten luoda taulut automaattisesti entiteettien perusteella
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2-selainkonsoli päälle (voit selata tietokantaa selaimessa)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console